/**
 * Compiles the Tailwind sheet and freezes it into a TypeScript module.
 *
 * Why go through a module rather than serve a `.css` file: the pages must stay
 * self-contained — a `<link>` tag would break the screen at the first network
 * outage, and a file read from disk at startup would not survive Electron
 * packaging (the defect has already cost one diagnosis on the migrations folder).
 * A constant inlined into the bundle cannot go missing.
 */
import { execFileSync } from 'node:child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const module = join(root, 'src', 'generated', 'styles.ts')

/**
 * Compiles the sheet and returns the CSS.
 *
 * Exported so the test can replay exactly the same compilation and compare: a
 * class added to a page without regenerating the sheet would have no style at
 * all and would raise nothing.
 */
export function compileCss(output = join(root, 'src', 'generated', 'styles.css')) {
  mkdirSync(dirname(output), { recursive: true })
  execFileSync(
    join(root, 'node_modules', '.bin', 'tailwindcss'),
    ['--input', join(root, 'src', 'theme.css'), '--output', output, '--minify'],
    { stdio: 'inherit', cwd: root },
  )
  return readFileSync(output, 'utf8').trim()
}

/** Escapes what would close the `<style>` tag of the page inlining it. */
export const escapeForStyleTag = (css) => css.replace(/<\/style>/gi, '<\\/style>')

// Run directly: regenerates the committed module.
if (process.argv[1] === fileURLToPath(import.meta.url)) writeModule()

function writeModule() {
  const css = compileCss()

  writeFileSync(
    module,
    [
      '// Generated by `pnpm --filter @cloudnord/ui build`. Do not edit by hand.',
      '// Regenerate after adding Tailwind classes to a page.',
      '',
      `export const TAILWIND_CSS = ${JSON.stringify(escapeForStyleTag(css))}`,
      '',
    ].join('\n'),
  )
  console.log(`sheet compiled: ${(css.length / 1024).toFixed(1)} kB → src/generated/styles.ts`)
}
