/**
 * Freezes the state machine into a TypeScript module, for the build-less pages.
 *
 * Same reason as the Tailwind sheet of `@cloudnord/ui`: the pages must stay
 * self-contained. A `<script src>` tag would break the control app at the first
 * network outage, and a file read from disk at startup would not survive
 * Electron packaging. A constant inlined into the bundle cannot go missing.
 *
 * The output format is an IIFE that sets `RoomState` on `globalThis`: the pages
 * are a single large `<script>` with no modules, and `import` has no currency
 * there.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildSync } from 'esbuild'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const module = join(root, 'src', 'generated', 'browser.ts')

/**
 * Compiles the browser entry point and returns the JavaScript.
 *
 * Exported so the test can replay exactly the same compilation and compare: a
 * rule changed in the state machine without regenerating the module would leave
 * the pages running on the old one — that is, exactly the divergence this
 * package exists to remove.
 */
export function compileBrowserBundle() {
  const result = buildSync({
    entryPoints: [join(root, 'src', 'browser.ts')],
    /**
     * Anchored at the repository root, otherwise the output depends on where it
     * is called from.
     *
     * esbuild writes each module's path as a comment, relative to the current
     * directory: compiled from the root or from the package, the bundle differed
     * on five comment lines, and the freshness test failed without anything
     * having changed.
     */
    absWorkingDir: join(root, '..', '..'),
    bundle: true,
    format: 'iife',
    globalName: 'RoomState',
    /**
     * Set explicitly on `globalThis`, and not merely declared with `var`.
     *
     * A top-level `var` becomes a global in a page, but stays local when the
     * script is replayed inside a `new Function` — which is what the page tests
     * do, since `innerHTML` does not execute `<script>` tags. The console then
     * rendered an empty room list, silently, and the test that should have
     * caught it only saw a `querySelector` with no result.
     */
    footer: { js: 'globalThis.RoomState = RoomState;' },
    platform: 'browser',
    target: 'es2022',
    // Readable: the page is a diagnostic tool as much as a screen, and a
    // minified blob in the console of a room machine cannot be inspected.
    minify: false,
    legalComments: 'none',
    write: false,
  })

  const output = result.outputFiles?.[0]
  if (output == null) throw new Error('esbuild produced nothing')
  return output.text.trim()
}

/** Escapes what would close the `<script>` tag of the page inlining it. */
export const escapeForScriptTag = (js) => js.replace(/<\/script>/gi, '<\\/script>')

// Run directly: regenerates the committed module.
if (process.argv[1] === fileURLToPath(import.meta.url)) writeModule()

function writeModule() {
  const js = escapeForScriptTag(compileBrowserBundle())

  mkdirSync(dirname(module), { recursive: true })
  writeFileSync(
    module,
    [
      '// Generated by `pnpm --filter @cloudnord/room-state build`. Do not edit by hand.',
      '// Regenerate after any change to src/browser.ts or to what it exports.',
      '',
      `export const MACHINE_JS = ${JSON.stringify(js)}`,
      '',
    ].join('\n'),
  )
  console.log(`state machine compiled: ${(js.length / 1024).toFixed(1)} kB → src/generated/browser.ts`)
}

/** Reads the committed module back, for tests that want to compare it. */
export function readModule() {
  return readFileSync(module, 'utf8')
}
