import { DEFAULT_EVENT_IDENTITY, type EventIdentity } from '@conference-operator/contract'

export interface ServiceWorkerOptions {
  /**
   * The event's identity, frozen into the worker at the moment it is served.
   *
   * A pushed notice sometimes arrives with no readable payload: it is then the
   * only name the worker has to title the notification. Reading it from the hub
   * rather than hard-coding it is what lets the same binary serve two events.
   */
  event?: EventIdentity
}

/**
 * The console's service worker.
 *
 * Its only reason to exist: receiving a notification when the console is closed.
 * It caches nothing — the console is served by the hub it drives, and a cache
 * would make it lie about the state of the rooms, which is exactly what it is
 * supposed to say.
 *
 * Served at the root (`/sw.js`) and not under `/admin/`: a service worker's
 * scope is that of its path, and a worker served under `/admin/` would not cover
 * the hub's other pages.
 */
export function renderServiceWorker(options: ServiceWorkerOptions = {}): string {
  const identity = options.event ?? DEFAULT_EVENT_IDENTITY
  return `/* Generated by the hub — see src/pages/service-worker.ts */
self.addEventListener('install', () => self.skipWaiting())
self.addEventListener('activate', (event) => event.waitUntil(self.clients.claim()))

self.addEventListener('push', (event) => {
  /*
   * A notice with no readable body is still a notice.
   *
   * Some push services wake the worker with no payload; staying silent then
   * would be the worst of both worlds — the phone buzzed, and the screen says
   * nothing.
   */
  let notice = { title: ${JSON.stringify(identity.shortName)}, body: 'Quelque chose a changé sur le hub.', tag: 'hub' }
  try {
    if (event.data) notice = { ...notice, ...event.data.json() }
  } catch {}

  event.waitUntil(
    self.registration.showNotification(notice.title, {
      body: notice.body,
      // The same tag as the page's notifications: when the console is open *and*
      // subscribed, the second notice replaces the first instead of stacking the
      // same information twice.
      tag: notice.tag,
      lang: 'fr',
      data: { view: notice.view ?? 'exploitation' },
    }),
  )
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const view = (event.notification.data && event.notification.data.view) || 'exploitation'
  const target = view === 'exploitation' ? '/admin' : '/admin/' + view

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windows) => {
      // A console that is already open is brought to the front rather than
      // duplicated: two tabs refreshing in parallel end up showing two different
      // states.
      for (const client of windows) {
        if (client.url.includes('/admin')) {
          return client.focus().then((focused) => focused.navigate(target))
        }
      }
      return self.clients.openWindow(target)
    }),
  )
})
`
}
