/**
 * Freezes the projected page's script and stylesheet into a TypeScript module.
 *
 * The same reason as the state machine of `@conference-operator/room-state`: the
 * page is served standalone by the room machine, inlined, with no network — a
 * constant compiled into the bundle cannot go missing. The source stays real
 * TypeScript and real CSS, which a template string in a page could not be.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildSync } from 'esbuild'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const module = join(root, 'src', 'generated', 'projector.ts')

/** The stylesheets, in cascade order: the reference first, this screen's additions after. */
export const STYLES = ['reference.css', 'screen.css']

export function compileScript() {
  const result = buildSync({
    entryPoints: [join(root, 'src', 'browser', 'main.ts')],
    // Anchored at the repository root, so the output does not depend on where it is called from.
    absWorkingDir: join(root, '..', '..'),
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2022',
    // Readable: a projector page is a diagnostic tool too.
    minify: false,
    legalComments: 'none',
    write: false,
  })
  const output = result.outputFiles?.[0]
  if (output == null) throw new Error('esbuild produced nothing')
  return output.text.trim()
}

export function compileStyles() {
  return STYLES.map((file) => readFileSync(join(root, 'src', 'styles', file), 'utf8').trim()).join('\n\n')
}

/** Escapes what would close the tag of the page inlining it. */
export const escapeForTag = (text, tag) => text.replace(new RegExp(`</${tag}`, 'gi'), `<\\/${tag}`)

export function renderModule() {
  const js = escapeForTag(compileScript(), 'script')
  const css = escapeForTag(compileStyles(), 'style')
  return [
    '// Generated by `pnpm --filter @conference-operator/projector build`. Do not edit by hand.',
    '// Regenerate after any change to src/browser or src/styles.',
    '',
    `export const PROJECTOR_JS = ${JSON.stringify(js)}`,
    '',
    `export const PROJECTOR_CSS = ${JSON.stringify(css)}`,
    '',
  ].join('\n')
}

export function readModule() {
  return readFileSync(module, 'utf8')
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const text = renderModule()
  mkdirSync(dirname(module), { recursive: true })
  writeFileSync(module, text)
  console.log(`projector compiled: ${(text.length / 1024).toFixed(1)} kB → src/generated/projector.ts`)
}
