/**
 * Freezes the projected page's script and stylesheet into a TypeScript module.
 *
 * The same reason as the state machine of `@conference-operator/room-state`: the
 * page is served standalone by the room machine, inlined, with no network — a
 * constant compiled into the bundle cannot go missing. The source stays real
 * TypeScript and real CSS, which a template string in a page could not be.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildSync } from 'esbuild'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

/**
 * The pages compiled: the projected loop, and the VOD's intro and outro, which
 * reuse its effects and circles but not its engine. The VOD's stylesheet is only
 * its own: its document inlines the loop's before it.
 */
export const MODULES = {
  projector: { entry: 'browser/main.ts', styles: ['reference.css', 'screen.css'], js: 'PROJECTOR_JS', css: 'PROJECTOR_CSS' },
  vod: { entry: 'vod/browser.ts', styles: ['vod.css'], js: 'VOD_JS', css: 'VOD_CSS' },
}

const modulePath = (name) => join(root, 'src', 'generated', `${name}.ts`)

/** The stylesheets, in cascade order: the reference first, this screen's additions after. */
export const STYLES = MODULES.projector.styles

export function compileScript(name = 'projector') {
  const result = buildSync({
    entryPoints: [join(root, 'src', MODULES[name].entry)],
    // Anchored at the repository root, so the output does not depend on where it is called from.
    absWorkingDir: join(root, '..', '..'),
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2022',
    // Readable: a projector page is a diagnostic tool too.
    minify: false,
    legalComments: 'none',
    write: false,
  })
  const output = result.outputFiles?.[0]
  if (output == null) throw new Error('esbuild produced nothing')
  return output.text.trim()
}

export function compileStyles(name = 'projector') {
  return MODULES[name].styles.map((file) => readFileSync(join(root, 'src', 'styles', file), 'utf8').trim()).join('\n\n')
}

/** Escapes what would close the tag of the page inlining it. */
export const escapeForTag = (text, tag) => text.replace(new RegExp(`</${tag}`, 'gi'), `<\\/${tag}`)

export function renderModule(name = 'projector') {
  const js = escapeForTag(compileScript(name), 'script')
  const css = escapeForTag(compileStyles(name), 'style')
  return [
    '// Generated by `pnpm --filter @conference-operator/projector build`. Do not edit by hand.',
    '// Regenerate after any change to src/browser, src/vod or src/styles.',
    '',
    `export const ${MODULES[name].js} = ${JSON.stringify(js)}`,
    '',
    `export const ${MODULES[name].css} = ${JSON.stringify(css)}`,
    '',
  ].join('\n')
}

export function readModule(name = 'projector') {
  return readFileSync(modulePath(name), 'utf8')
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  for (const name of Object.keys(MODULES)) {
    const text = renderModule(name)
    mkdirSync(dirname(modulePath(name)), { recursive: true })
    writeFileSync(modulePath(name), text)
    console.log(`${name} compiled: ${(text.length / 1024).toFixed(1)} kB → src/generated/${name}.ts`)
  }
}
